// app/page.tsx
import Link from 'next/link';

export default function Home() {
  return (
    <div className="container">
      <div className="header">
        <h1>aperture</h1>
      </div>
      <div className="subheader">
        <p>The only hub for .huh, fenrir and many more projects! a product of yigit.</p>
      </div>
      <nav>
        <Link href="https://github.com/yigitkabak" className="nav-link">github</Link>
      </nav>
      <footer>
        <p>a yigit production.</p>
      </footer>
    </div>
  );
}

// src/App.svelte
<!-- App.svelte -->
<script lang="ts">
  import Css from './scripts/css.svelte';
  import Header from './scripts/header.svelte';
  import Nav from './scripts/nav.svelte';
  import Footer from './scripts/footer.svelte';
</script>

<div class="container">
 <Header />
 <div class="subheader">
    <p>The only hub for <a href="https://github.com/yigitkabak/huh">.huh</a>, <a href="https://github.com/yigitkabak/aperium">aperium</a> and many more projects! a product of yigit.</p>
  </div>
 <Nav />
 <Footer />
</div>

<Css />
